VAGRANT_API_VERSION = 2

Vagrant.require_version ">= 2"

required_plugins = %w( vagrant-vbguest )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "centos/7"

  #WebServer
  config.vm.define "web", primary: true do |webserver|
    webserver.vm.hostname = "WebServer"

    webserver.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end

    webserver.vm.network "forwarded_port", guest: 80, host: 8080 #Web you can change to 80
    webserver.vm.network "forwarded_port", guest: 443, host: 8081 #ssl
    webserver.vm.network "forwarded_port", guest: 3306, host: 8082 #MySQL

    webserver.vm.synced_folder "../ansible", "/ansible",
        id: "ansible-folder", 
        :nfs => true

    webserver.vm.synced_folder "../shared", "/shared",
        id: "shared-folder", 
        :nfs => true

    webserver.vm.synced_folder "../sites", "/var/www", 
        id: "sites-folder", 
        :nfs => true, 
        :mount_options => ['rw', 'vers=3', 'tcp', 'fsc', 'actimeo=2']

    webserver.vm.network "private_network", ip: "192.168.50.10" #VirtualHost1
    webserver.vm.network "private_network", ip: "192.168.50.20" #VirtualHost1
    
    webserver.vm.provision :shell, path: "provision/provision.sh" #Install Ansible
    webserver.vm.provision :shell, path: "provision/web.sh" #Install roles and execute ansible

    webserver.vm.provision "shell", inline: "sudo apachectl start", run: "always"
  end

  #ElasticSearch, Kibana y Redis
  config.vm.define "services", primary: true do |services|
    services.vm.hostname = "ServiceServer"

    services.vm.provider :virtualbox do |vb|
        vb.memory = 3096
        vb.cpus = 2
    end
    
    services.vm.network "forwarded_port", guest: 9200, host: 9200 #ElasticSearch
    services.vm.network "forwarded_port", guest: 5601, host: 5601 #Kibana 
    services.vm.network "forwarded_port", guest: 5672, host: 5672 #Rabbit
    services.vm.network "forwarded_port", guest: 5673, host: 5673 #Rabbit
    services.vm.network "forwarded_port", guest: 15672, host: 15672 #Rabbit
    services.vm.network "forwarded_port", guest: 6379, host: 6379 #Redis

    services.vm.synced_folder "../ansible", "/ansible",
        id: "ansible-folder-services", 
        :nfs => true

    services.vm.synced_folder "../shared", "/shared",
        id: "shared-folder-services", 
        :nfs => true

    services.vm.network "private_network", ip: "192.168.50.100" #Services
    
    services.vm.provision :shell, path: "provision/provision.sh" #Install Ansible and roles
    services.vm.provision :shell, path: "provision/services.sh" #Install roles and execute ansible

    services.vm.provision "shell", inline: "sudo /sbin/chkconfig --add elasticsearch", run: "always"
    services.vm.provision "shell", inline: "sudo service elasticsearch start", run: "always"
  end
end
